name: Build and Release LeetViewer

on:
  push:
    tags:
      - "v*.*.*" # Trigger workflow on version tags like v1.0.0

jobs:
  build:
    name: Build LeetViewer on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            cmake-generator: "Unix Makefiles"
            os-name: "linux"
          - os: macos-latest
            cmake-generator: "Unix Makefiles"
            os-name: "macos"
          - os: windows-latest
            cmake-generator: "MinGW Makefiles"
            os-name: "windows"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: "3.x"

      # Install dependencies for Ubuntu (Linux)
      - name: Install dependencies on Ubuntu (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libncurses5-dev libncursesw5-dev g++

      # Install dependencies for macOS
      - name: Install dependencies on macOS
        if: matrix.os == 'macos-latest'
        run: |
          brew install ncurses cmake

      # Install PDCurses for Windows
      - name: Install PDCurses on Windows
        if: matrix.os == 'windows-latest'
        run: |
          git clone https://github.com/wmcbrine/PDCurses.git
          cd PDCurses/wincon
          if (Test-Path "Makefile") {
              mingw32-make -f Makefile
              mkdir ../../pdcurses_install
              Move-Item pdcurses.a ../../pdcurses_install/
              echo "::set-env name=PDCURSES_DIR::$(pwd)\..\..\pdcurses_install"
          } else {
              Write-Host "Error: Makefile not found!"
              exit 1
          }

      # Configure CMake with the correct generator and PDCurses path on Windows
      - name: Configure CMake
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            cmake -G "${{ matrix.cmake-generator }}" -DPDCURSES_DIR=${{ env.PDCURSES_DIR }} .
          else
            cmake -G "${{ matrix.cmake-generator }}" .
          fi

      - name: Build the project
        run: cmake --build . --config Release

      - name: Rename and move the executable (Linux/macOS)
        if: matrix.os != 'windows-latest'
        run: mv ./LeetViewer ./LeetViewer-${{ matrix.os-name }}

      - name: Rename and move the executable (Windows)
        if: matrix.os == 'windows-latest'
        run: mv ./LeetViewer.exe ./LeetViewer-${{ matrix.os-name }}.exe

      - name: Upload the artifact
        uses: actions/upload-artifact@v3
        with:
          name: LeetViewer-${{ matrix.os-name }}
          path: |
            ./LeetViewer-${{ matrix.os-name }}
            ./LeetViewer-${{ matrix.os-name }}.exe

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./artifacts/LeetViewer-linux
            ./artifacts/LeetViewer-macos
            ./artifacts/LeetViewer-windows.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
